"""
Extracts OSM turn-restriction relations (type=restriction) relevant to the
ways in busan-roads_osm.pbf, from a full-country .osm.pbf - busan-roads_osm.pbf
itself has ZERO relations of any kind (confirmed by walking its primitive
groups), so turn restrictions are structurally impossible to enforce from
that file alone, regardless of routing-code changes. Writes a compact
turn_restrictions.json that graph_backend.py loads to block illegal turns
during A* search, the same way gov_restrictions.json/manual_restrictions.json
already feed height/weight/width restrictions.

Only "no_*" restrictions (no_left_turn, no_right_turn, no_straight_on,
no_u_turn) are extracted - these translate directly into "ban this one
(from_way, via_node, to_way) transition". "only_*" restrictions
(only_left_turn, etc - meaning every OTHER transition from that via_node/
from_way is banned) are a different, harder transform (need enumerating
every alternative way at that junction) and are deliberately NOT
implemented here - skipped with a logged count rather than guessed at,
since getting that wrong risks blocking legal turns, which is worse than
not enforcing the restriction at all.

Usage:
    python extract_turn_restrictions.py --source south-korea-latest.osm.pbf

Download the source (not committed to git - ~260MB) from
https://download.geofabrik.de/asia/south-korea.html - only needed to
regenerate turn_restrictions.json, never at app runtime.
"""
import argparse
import json

from pbf_parser import parse_pbf, parse_relations

NO_TYPES = {"no_left_turn", "no_right_turn", "no_straight_on", "no_u_turn"}
ONLY_TYPES = {"only_left_turn", "only_right_turn", "only_straight_on", "only_u_turn"}


def _member(members, role, mtype="way"):
    return next((ref for mt, ref, rl in members if mt == mtype and rl == role), None)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pbf", default="busan-roads_osm.pbf")
    ap.add_argument("--source", default="south-korea-latest.osm.pbf")
    ap.add_argument("--out", default="turn_restrictions.json")
    args = ap.parse_args()

    print(f"Loading way IDs from {args.pbf} ...")
    _, ways = parse_pbf(args.pbf)
    way_ids = {wid for wid, refs, tags in ways}
    print(f"  {len(way_ids)} ways")

    print(f"Parsing relations from {args.source} ...")
    relations = parse_relations(args.source)
    restriction_rels = [r for r in relations if r[2].get("type") == "restriction"]
    print(f"  {len(restriction_rels)} type=restriction relations nationwide")

    out = []
    skipped_only = 0
    skipped_incomplete = 0
    for rel_id, members, tags in restriction_rels:
        from_way = _member(members, "from")
        to_way = _member(members, "to")
        via_node = _member(members, "via", "node")
        restriction = tags.get("restriction", "")
        if not (from_way and to_way and via_node):
            skipped_incomplete += 1
            continue
        if from_way not in way_ids and to_way not in way_ids:
            continue  # not relevant to this extract
        if restriction in ONLY_TYPES:
            skipped_only += 1
            continue
        if restriction not in NO_TYPES:
            continue
        out.append({
            "from_way": from_way, "via_node": via_node, "to_way": to_way,
            "restriction": restriction,
        })

    print(f"  {len(out)} usable no_* restrictions relevant to {args.pbf}")
    print(f"  {skipped_only} only_* restrictions skipped (not yet supported - see module docstring)")
    print(f"  {skipped_incomplete} skipped nationwide (missing from/via_node/to member)")

    with open(args.out, "w", encoding="utf-8") as f:
        json.dump({
            "_readme": (
                "Auto-generated by extract_turn_restrictions.py from OSM turn-restriction "
                "relations (type=restriction) in a full-country extract, filtered to "
                "restrictions touching a way in busan-roads_osm.pbf. Only no_* restriction "
                "types are included - only_* types are not yet supported, see the script's "
                "module docstring for why."
            ),
            "restrictions": out,
        }, f, ensure_ascii=False, indent=2)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
